---

- hosts: localhost

  vars:
    local_username: kali

  tasks:
    - name: tune system swappiness
      ansible.posix.sysctl:
        name: vm.swappiness
        value: '0'
        state: present

    - name: install some recommended additional packages
      ansible.builtin.apt:
        pkg:
          - seclists
          - linux-exploit-suggester
          - mat2
          - sshuttle
          - bettercap
          - sslstrip
          - tree
          - parallel
          - meld
          - gobuster
          - chromium

    - block:
        - name: Install tldr package
          ansible.builtin.apt:
            pkg:
              - tldr

        - name: create parent directories required for tldr doc files
          ansible.builtin.file:
            path: "~{{ local_username  }}/.local/share"
            state: directory
          become: yes
          become_user: "{{ local_username }}"

        - name: Clone tldr doc file repo
          ansible.builtin.command: tldr --update
          become: yes
          become_user: "{{ local_username }}"

    - block:
        - name: install python3-pip package
          ansible.builtin.apt:
            pkg:
              python3-pip

        - name: install some useful pip packages
          ansible.builtin.pip:
            name:
              - one-lin3r
            executable: pip3

    - block:
        - name: install tor and proxychains
          ansible.builtin.apt:
            pkg:
              - tor
              - proxychains4

        - name: copy torrc file
          ansible.builtin.copy:
            src: etc/tor/torrc
            dest: /etc/tor/torrc
            owner: root
            group: root
            mode: '0644'
            backup: yes

        - name: ensure tor service runs on system startup
          ansible.builtin.systemd:
            name: tor
            state: started
            enabled: yes

        - name: copy proxychains4 config file
          ansible.builtin.copy:
            src: etc/proxychains4.conf
            dest: /etc/proxychains4.conf
            owner: root
            group: root
            mode: '0644'
            backup: yes

    - block:
        - name: install packages needed for tmux with powerline
          ansible.builtin.apt:
            pkg:
              - tmux
              - powerline
              - python3-powerline
              - xclip

        - name: copy sample .tmux.conf file to the user's homedir
          ansible.builtin.copy:
            src: home/user/.tmux.conf
            dest: "~{{ local_username }}/.tmux.conf"
          become: yes
          become_user: "{{ local_username }}"
