---

- hosts: localhost

  tasks:
    - name: install some recommended additional packages
      apt:
        pkg:
          - seclists
          - linux-exploit-suggester
          - mat2
          - sshuttle
          - bettercap
          - sslstrip

    - block:
        - name: install python3-pip package
          apt:
            pkg:
              python3-pip

        - name: install some useful pip packages
          pip:
            name:
              - one-lin3r
            executable: pip3

    - block:
        - name: install tor and proxychains
          apt:
            pkg:
              - tor
              - proxychains4

        - name: copy torrc file
          copy:
            src: etc/tor/torrc
            dest: /etc/tor/torrc
            owner: root
            group: root
            mode: '0644'
            backup: yes

        - name: ensure tor service runs on system startup
          service:
            name: tor
            state: started
            enabled: yes

        - name: copy proxychains4 config file
          copy:
            src: etc/proxychains4.conf
            dest: /etc/proxychains4.conf
            owner: root
            group: root
            mode: '0644'
            backup: yes
