---

- hosts: localhost

  vars:
    local_username: kali

  tasks:
    - name: tune system swappiness
      ansible.posix.sysctl:
        name: vm.swappiness
        value: '0'
        state: present

    - name: perform a dist upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: install some recommended additional packages
      ansible.builtin.apt:
        pkg:
          - seclists
          - payloadsallthethings
          - linux-exploit-suggester
          - mat2
          - sshuttle
          - bettercap
          - sslstrip
          - tree
          - parallel
          - meld
          - gobuster
          - chromium
          - nishang
          - 2to3
          - rlwrap
          - bat
          - burpsuite
          - hashrat
          - name-that-hash

    - block:
        - name: Gather the package facts
          ansible.builtin.package_facts:
            manager: auto
          no_log: true

        - name: Print the package facts
          ansible.builtin.debug:
            var: ansible_facts.packages
          no_log: true

        - name: Create symlink to seclists from wordlists dir
          ansible.builtin.file:
            src: /usr/share/seclists
            dest: /usr/share/wordlists/seclists
            state: link
          when: "'seclists' in ansible_facts.packages"

    - block:
        - name: install python3-pip package
          ansible.builtin.apt:
            pkg:
              python3-pip

        - name: install some useful pip packages
          ansible.builtin.pip:
            name:
              - one-lin3r
              - tldr
            executable: pip3

    - block:
        - name: install tor and proxychains
          ansible.builtin.apt:
            pkg:
              - tor
              - proxychains4

        - name: copy torrc file
          ansible.builtin.copy:
            src: etc/tor/torrc
            dest: /etc/tor/torrc
            owner: root
            group: root
            mode: '0644'
            backup: true

        - name: ensure tor service runs on system startup
          ansible.builtin.systemd:
            name: tor
            state: started
            enabled: true

        - name: copy proxychains4 config file
          ansible.builtin.copy:
            src: etc/proxychains4.conf
            dest: /etc/proxychains4.conf
            owner: root
            group: root
            mode: '0644'
            backup: true

    - block:
        - name: install packages needed for tmux with powerline
          ansible.builtin.apt:
            pkg:
              - tmux
              - powerline
              - python3-powerline
              - xclip

        - name: copy sample .tmux.conf file to the user's homedir
          ansible.builtin.copy:
            src: home/user/.tmux.conf
            dest: "~{{ local_username }}/.tmux.conf"
            mode: '0644'
          become: true
          become_user: "{{ local_username }}"

    - name: add kali user to kali-trusted group for passwordless sudo
      ansible.builtin.user:
        name: kali
        groups: kali-trusted
        append: true

    - block:
        - name: install nmapAutomator script
          ansible.builtin.git:
            repo: 'https://github.com/21y4d/nmapAutomator.git'
            dest: /opt/nmapAutomator
            clone: true
            version: master

        - name: make nmapAutomator available in /usr/local/bin/
          ansible.builtin.file:
            src: /opt/nmapAutomator/nmapAutomator.sh
            dest: /usr/local/bin/nmapAutomator.sh
            state: link

    - block:
        - name: create base dir for privesc scripts
          ansible.builtin.file:
            path: /opt/privesc-scripts
            state: directory
            mode: '0775'

        - name: create symlink from /usr/share
          ansible.builtin.file:
            src: /opt/privesc-scripts
            dest: /usr/share/privesc-scripts
            state: link

        - name: git clone PEASS-ng
          ansible.builtin.git:
            repo: 'https://github.com/carlospolop/PEASS-ng.git'
            dest: /opt/privesc-scripts/PEASS-ng
            clone: true
            version: master

        - name: git clone LinEnum
          ansible.builtin.git:
            repo: 'https://github.com/rebootuser/LinEnum.git'
            dest: /opt/privesc-scripts/LinEnum
            clone: true
            version: master

        - name: git clone linux-smart-enumeration
          ansible.builtin.git:
            repo: 'https://github.com/diego-treitos/linux-smart-enumeration'
            dest: /opt/privesc-scripts/linux-smart-enumeration
            clone: true
            version: master

        - name: git clone linux-exploit-suggester
          ansible.builtin.git:
            repo: 'https://github.com/mzet-/linux-exploit-suggester.git'
            dest: /opt/privesc-scripts/linux-exploit-suggester
            clone: true
            version: master
